name = "devbox"
uidn = "super"
cli = "podman"

[volume]
bin = "/Users/nero/Home/bin"
data = "/Users/nero/Home/data"
nuts = "/Users/nero/Home/nuts"
repos = "/Users/nero/Home/repos"
stuff = "/Users/nero/Home/stuff"
box = "/Users/nero/Home/box"
